wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706666602.650041
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 13
      - 23
      4: 3.8.5
      5: 0.16.2
      6: 4.26.0
      8:
      - 1
      - 5
      13: linux-x86_64
